# Generated by Django 5.0 on 2024-01-15 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bank_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="aDate",
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
