# Generated by Django 5.0 on 2024-01-16 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bank_app", "0002_alter_account_adate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="aDate",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
