# Generated by Django 5.0 on 2024-01-19 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bank_app", "0006_rename_hasaccount_trackaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tDate", models.DateField()),
                ("tDescription", models.CharField(max_length=20)),
                ("tBalance", models.IntegerField()),
                (
                    "tAccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Bank_app.account",
                    ),
                ),
            ],
        ),
    ]
