# Generated by Django 5.0 on 2024-01-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bank_app", "0007_transactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="tBalance",
            field=models.FloatField(),
        ),
    ]
